<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_scroll.html_shadow_host</name>
   <tag></tag>
   <elementGuidId>da52814f-2e4c-4a0a-910c-1745755baaa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shadow_host']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shadow_host</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f7adf51-8539-43c2-b9d5-8f2c7f04ab29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shadow_host</value>
      <webElementGuid>16d130c7-4ed8-41e1-8420-f2e234888dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shadow_host&quot;)</value>
      <webElementGuid>1d18c99e-059a-491f-a694-73e063102730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='shadow_host']</value>
      <webElementGuid>3eb61902-923a-4620-8d87-b9ddcb6de067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
      <webElementGuid>1bb9fe4d-9911-4f3c-a749-aacf856ff67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shadow_host']</value>
      <webElementGuid>fa247b50-266a-4740-8378-6ef85faadfd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
