<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Page 1</name>
   <tag></tag>
   <elementGuidId>6df6c860-68ba-4cc8-ba45-7113793e3021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#page1' and (text() = 'Page 1' or . = 'Page 1')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navigation']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cabbec4-725d-4ab1-9a0f-8326bd6205a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#page1</value>
      <webElementGuid>59a21a54-160f-4ef5-bcf0-d76f6c0d95b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page 1</value>
      <webElementGuid>aef78308-9460-4a9b-a557-0aa41fdf5ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)/li[1]/a[1]</value>
      <webElementGuid>12e834d3-2ac5-4837-a195-0cbecf373009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navigation']/li/a</value>
      <webElementGuid>59972a35-def7-42b4-9c06-0a8352145487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Page 1')]</value>
      <webElementGuid>42ceb5d8-e6d3-4443-a7e5-1f866c85fa60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Because simpler is better'])[1]/following::a[1]</value>
      <webElementGuid>653c10ef-6b08-43c2-92bf-2a3f73ecca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A simple AJAX driven jQuery website'])[1]/following::a[1]</value>
      <webElementGuid>e51b32f1-9d74-4ed7-a7a2-9de9c6d3a9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 2'])[1]/preceding::a[1]</value>
      <webElementGuid>f0dd20bb-36d3-4e2c-a71a-d00ca6882e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 3'])[1]/preceding::a[2]</value>
      <webElementGuid>732aeca8-53bf-4fff-94bb-2e511377026e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#page1')]</value>
      <webElementGuid>45f023eb-c5d0-44e2-949d-f5de5dd8ccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>98f5aa9a-df04-4b47-a01e-88277d74252e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
