<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Page 2</name>
   <tag></tag>
   <elementGuidId>a21a64fb-552c-4e70-8054-479800181936</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#page2' and (text() = 'Page 2' or . = 'Page 2')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navigation']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8093065c-b0ed-4fc6-810d-df0e3c1ef8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#page2</value>
      <webElementGuid>f99bc37c-b61f-4a31-b87b-de5836e6b761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Page 2</value>
      <webElementGuid>b2d1886a-9401-46a6-a92f-e49cc7193c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation&quot;)/li[2]/a[1]</value>
      <webElementGuid>5792bd70-f420-41ce-bbe2-1a2e31daff1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navigation']/li[2]/a</value>
      <webElementGuid>aa5ea7d6-11da-44cd-98b7-6afe56999921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Page 2')]</value>
      <webElementGuid>34a0043c-1eec-4f7a-9e5c-fb4766934740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 1'])[1]/following::a[1]</value>
      <webElementGuid>f21a2c12-2245-43ec-b154-39e698b5edc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Because simpler is better'])[1]/following::a[2]</value>
      <webElementGuid>19fb11b9-68b7-4c52-b383-cf67744a3f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 3'])[1]/preceding::a[1]</value>
      <webElementGuid>8d5682ad-a178-42d5-b18b-62f7e8695a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page 4'])[1]/preceding::a[2]</value>
      <webElementGuid>784fd421-9529-40f8-9f10-63db1336d76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#page2')]</value>
      <webElementGuid>12246794-1da0-4cb4-a9d7-3466f48cff11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>663d0e71-4bdc-4816-bcad-5443c343ca81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
